sudo: required
language: generic
dist: trusty

env:
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPO=ros NOT_TEST_INSTALL=true CATKIN_LINT=true

install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh
